---
title: "practice basic ploting for language and data analysis"
output: html_notebook
---
```{r}
##Problem 1--------------------------------------------------------------
```
```{r df-drop, class.source='bg-warning', class.output='bg-warning'}
A<-array(c(1,2,3,4,5,6,7,8,9),dim=c(3,3))
B<-array(c(4,5,6,7,8,9,10,11,12,13,14,15),dim=c(4,3))
C<-array(c(8,9,10,8,9,10),dim=c(3,2))
A[,2]
B[,2]
C[,2]
A[1,]
B[1,]
C[1,]
```
```{r}
sum(A[,2])
sum(B[,2])
sum(C[,2])
sum(A[1,])
sum(B[1,])
sum(C[1,]) 
```
```{r}
##Problem 2--------------------------------------------------------------
```
```{r}
X<-c(1,2,3,4,5,6,7,8,9,10)
Y<-c(1,2,3,4,5,5,4,3,2,1)
plot(X,Y,type='p')
plot(X,Y,type='l')
plot(X,Y,type='b')
plot(X,Y,type='c')
plot(X,Y,type='o')
plot(X,Y,type='h')
```
```{r}
##Problem 3--------------------------------------------------------------
```
```{r}
hist(mtcars$mpg,main="Histogram of wt",xlab="wt",ylab="Frequency",col = 'blue')
hist(mtcars$wt,main="Histogram of mpg",xlab="mpg",ylab="Frequency",col = 'pink')
hist(mtcars$disp,main="Histogram of disp",xlab="disp",ylab="Frequency",col = 'yellow')

plot(mtcars$wt,mtcars$mpg,main="scatter plot 1",xlab="wt",ylab="mpg")
abline(lm(mpg~wt,data=mtcars),col='yellow')

plot(mtcars$disp,mtcars$mpg,main="scatter plot 2",xlab="disp",ylab="mpg")
abline(lm(mpg~disp,data=mtcars),col='red')
```